const fs = require("fs");
const path = require("path");

const manifestPath = path.join(__dirname, "manifest.json");
const swVersionPath = path.join(__dirname, "sw-version.js");

const manifest = {
  buildTime: Date.now(),
  app: "MealPlanner",
};

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

const cacheFiles = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js",
];

const swVersionSource = `// Auto-generated by build.js -- do not edit\nconst CACHE_VERSION = "${manifest.buildTime}";\nconst CACHE_FILES = ${JSON.stringify(cacheFiles, null, 2)};\n`;

fs.writeFileSync(swVersionPath, swVersionSource);

console.log("Generated manifest.json");
console.log("Generated sw-version.js (cache version: " + manifest.buildTime + ")");
