// Auto-generated by build.js -- do not edit
const CACHE_VERSION = "1785313471716";
const CACHE_FILES = [
  "./index.html",
  "./styles.css",
  "./app.js",
  "./supabase-config.js",
  "./manifest.json",
  "./sw.js"
];
